### ISSUE TITLE
Login page translations and password forgotten function

### ISSUE THREAD

**Issue by ekmatts1** [OpusCapita/businessnetwork#10]
![image](https://cloud.githubusercontent.com/assets/28104515/25794389/e2eb2b14-33d0-11e7-955f-bfaed1cf230d.png)
Login section after registration. Users are able to change language settings and renew their password if lost. Login page has a uniform look and feel with OpusCapita branding and logo. Export of “language table” from text blocks and single naming in order to translate content into DE, FI, and SE as primary target. Establish “swop” function in upper right corner to change language

**Comment by gr4per** [comment]
This should be split to two cards:
1) password forgotten 
2) translations and swap
