### ISSUE TITLE
Upload of contact for onboarding campaigns

### ISSUE THREAD

**Issue by ekmatts1** [OpusCapita/businessnetwork#16]
![image](https://cloud.githubusercontent.com/assets/28104515/25795035/cf312756-33d3-11e7-8163-7bd87b944f78.png)
How to parse/match a contact list i.e. "name; address 1,2..; phone; email .." to already sent recipients i.e. buyer should be able to upload a new contact list and match it against already performed campaigns.

**Comment by gr4per** [comment]
We need to add instructions on the import tab.
I think some info about what column names we support in excel for what contact field
Also place a excel template with columns for all contactFields that we support for import (all except technical fields filled later, such as status, userId, supplierId, invitationCode)
The excel should contain sample records of course
