### ISSUE TITLE
Restrict all apis to be tenant local

### ISSUE THREAD

**Issue by gr4per** [OpusCapita/businessnetwork#17]
All apis may only return data belonging to the tenant of user querying.
Exceptions:
* Supplier/customer  header can be read by other tenant users  (but none of the one-to-many relations)
* users in role xtenant can see all tenant data
* data that doesn't belong to a tenant (no customerId/supplierId) is considered global and readable by everyone but not editable  (example: countries)

**Comment by gr4per** [comment]
Also interesting to complete access level requirements, we could use something like
https://github.com/nyambati/express-acl

**Comment by kwierchris** [comment]
Looks like is not compatible with our system. It requires special properties to be set to the request object and seems to only support a *role* property inside the web-token that can only contain one role (string) inside and not a list like our system supports.

**Comment by gr4per** [comment]
done for public apis, other use explicit tenant in order to benefit from acl
