### ISSUE TITLE
Add blob service for tenant files

### ISSUE THREAD

**Issue by gr4per** [OpusCapita/businessnetwork#19]
Blob service will encapsulate Azure blob api.
We should use one blob per tenant.
We need public and private sub folders. 

Files are considered data and should be in service specific path
Example:
Email templates for onboarding service -> blob/private/c_ncc/onboarding/campaigns/eInvoiceSupplierOnboarding/:templateId/files
Logo for customer -> blob/public/c_ncc/images/logo.png
Background image for landing page -> blob/public/c_ncc/onboarding/campaigns/:campaignType/landingPageBackground.png
Spec here
https://docs.google.com/document/d/17OsivCVNJCW6NUp5OFcbJDfEwJdCXUWY0sjyikiQGcM/edit#

Implemented by
https://github.com/OpusCapita/blob/issues/1

**Comment by gr4per** [comment]
implemented by
https://github.com/OpusCapita/onboarding/issues/98

**Comment by kwierchris** [comment]
In order to create the support document for creating customers I specified the following now:

As every tenant has an isolated container inside azure blob, we do not have to put the tenant id into the path because it would be redundant. Here is how I set the paths for the support document.

Logo path:
**/public/images/logo.png**

Background image path: **/public/onboarding/campaigns/eInvoiceSupplierOnboarding/landingPageBackground.png**

**Comment by gr4per** [comment]
Patryk is implementing this, so you have to finally adjust the path to whatever he puts in code.


Von: Christian Drengenberg [mailto:notifications@github.com]
Gesendet: Donnerstag, 29. Juni 2017 09:30
An: OpusCapita/businessnetwork <businessnetwork@noreply.github.com>
Cc: Gräper Arne <Arne.Graeper@opuscapita.com>; Author <author@noreply.github.com>
Betreff: Re: [OpusCapita/businessnetwork] Add blob service for tenant files (#19)


In order to create the support document for creating customers I specified the following now:

As every tenant has an isolated container inside azure blob, we do not have to put the tenant id into the path because it would be redundant. Here is how I set the paths for the support document.

Logo path:
/public/images/logo.png

Background image path: /public/onboarding/campaigns/eInvoiceSupplierOnboarding/landingPageBackground.png
