### ISSUE TITLE
Service2Service calls security

### ISSUE THREAD

**Issue by gr4per** [OpusCapita/businessnetwork#2]
Ensure services call other services either
1. *on behalf of user* 
directly (via endpoint discovery) forwarding ID Token from original user request 
2. *privileged*
indirectly via kong, going through auth flow to get access token

Also
Ensure all services properly protect exposed apis based on user/role/permission model

- [ ] OpusCapitaBusinessNetwork/api-gw#10

**Comment by kwierchris** [comment]
The easiest way to pass on authentication would be using the ServiceClient instance provided by web-init. If not disabled, there is a **req.ocbesbn.serviceClient** object available with default headers already added. [web-init.DefaultConfig](https://github.com/OpusCapitaBusinessNetwork/web-init/wiki#module_ocbesbn-web-init.DefaultConfig)
