### ISSUE TITLE
Email template design

### ISSUE THREAD

**Issue by ekmatts1** [OpusCapita/businessnetwork#24]
![image](https://cloud.githubusercontent.com/assets/28104515/25797307/e8baa87e-33dc-11e7-81f0-e7fc32408a08.png)
Work and adjust the template to support OC design guideline. Adjust font, font size and spacing between lines.

**Comment by patrykkopycinski** [comment]
Hi @ekmatts1, could you add link do OC design guideline?

**Comment by ekmatts1** [comment]
[OpusCapita_Graphic_guidelines_for_web_services_2.0.pdf](https://github.com/OpusCapita/businessnetwork/files/983801/OpusCapita_Graphic_guidelines_for_web_services_2.0.pdf)
http://brandbank.opuscapita.com/f/r6KQ

Added link to OC Brandbank above @patrykkopycinski - can you access it?

**Comment by ekmatts1** [comment]
Also here https://opuscapita.github.io/ocui/index.html you can find more @patrykkopycinski in addition to 
https://github.com/OpusCapita/oc-common-ui and https://opuscapita.github.io/

**Comment by ekmatts1** [comment]
Please feel free to share this with your team and for questions, feedback, contact Maarit Mannonen whom has contact with Branding team to align and share styles, colours, icons and so on in order to keep also OC website and other tools and documents consistent across the company @patrykkopycinski

**Comment by gr4per** [comment]
I have the impression this is about changing the customer specific template into a generic template that could be used for various customers ?
If not, what is the point of having OC specific rules in customer email templates when we will allow them to put arbitrary html ?

**Comment by ekmatts1** [comment]
I just wanted to share the common guidelines and what other units are working with - but exactly @gr4per - the idea is that we have the knowledge about the most useful wording and setup of an onboarding letter and it´s only customer specific details that are allowed to be changed as we have it right now - in addition, I have compiled a more "light" letter to use without argumentation.

**Comment by gr4per** [comment]
https://github.com/OpusCapita/onboarding/issues/110

**Comment by gr4per** [comment]
onboarding #110 is done
