### ISSUE TITLE
Landing page - Customization

### ISSUE THREAD

**Issue by ekmatts1** [OpusCapita/businessnetwork#25]
![image](https://cloud.githubusercontent.com/assets/28104515/25797402/5acbca38-33dd-11e7-9f9c-fa964acc100d.png)
How to be build a generic landing page giving customers the ability to upload logos and adjust color according to their brand guidlines?

**Comment by gr4per** [comment]
potential duplicate, this is related to tenant specific storage of html and related files.
We could even support having an fully external landing page (just a link to an agency hosted site)

**Comment by gr4per** [comment]
Implemented by 
https://github.com/OpusCapita/onboarding/issues/101

**Comment by gr4per** [comment]
done
