### ISSUE TITLE
Add simple Email template to "Create Campaign"

### ISSUE THREAD

**Issue by ekmatts1** [OpusCapita/businessnetwork#26]
![image](https://cloud.githubusercontent.com/assets/28104515/25798155/5573c79a-33e0-11e7-8b4e-87b720565ba9.png)

Subject:  New guidelines for invoicing NCC XX

NCC is moving to electronic invoicing.

As one of our valued suppliers, you are receiving this information. If you are not the right person to receive this letter, please forward it to Invoice handling department or department of Finance. 

Due to our new invoicing guidelines, NCC will from 2017-XX-XX on use electronic invoice format as the preferred alternative and by end of the year 2017 the only option for receiving your invoices. 
Our goal is to reduce costs both for us as a company and for you as a supplier. Moving to e-invoicing will contribute to shortening the invoice process, faster payments, and improved quality. In addition, our joint efforts will contribute in a significant way to the environment. 

We offer our suppliers several options for sending invoices to NCC XX available on the following site after registration - http://52.174.28.41:8080/registration

![image](https://cloud.githubusercontent.com/assets/28104515/25798210/85c21168-33e0-11e7-8efc-b929a6a08345.png)

We kindly ask you to confirm your readiness to send e-invoices to NCC by 2017-XX-XX. 

For more information about our transition to electronic invoicing, visit our web page. 

Thank you for supporting our initiative to increase e-invoicing! 

Best Regards 
Name Surname -Chief Accountant Phone: 
+47 01 01 01 01 (direct) 
E-mail: name.surname@customer.com 
Signature

**Comment by gr4per** [comment]
The problem here is that we dont have the signature for the template.
Name Surname -Chief Accountant Phone:
+47 01 01 01 01 (direct)
E-mail: name.surname@customer.com
Signature

we could inject the contact details of the supplieradmin

else we would need to setup specific fields for these in Campaign to be edited by user.

**Comment by gr4per** [comment]
i think we cover this already
