### ISSUE TITLE
Service configuration flow - services by june

### ISSUE THREAD

**Issue by ekmatts1** [OpusCapita/businessnetwork#27]
![image](https://cloud.githubusercontent.com/assets/28104515/25798399/542ca8e2-33e1-11e7-91de-5245211bda99.png)
Enable choice of Invoice Digitizing and email receiving as primary target for june release. Dependent on available services from messaging platform additional services as eInvoice and Invoice portal maybe scoped.

**Comment by gr4per** [comment]
this depends heavily on product, so we will miss the june milestone.
what we can do:
* generic data models in place
* lifecylce events for serviceConfig and customerContract
* integrate supplier connection and service config data to supplier dashboard / campaign dashboard
* include customer pdf or html conditions in last page of process

**Comment by gr4per** [comment]
done
