### ISSUE TITLE
SupplierCustomer Contract

### ISSUE THREAD

**Issue by ekmatts1** [OpusCapita/businessnetwork#28]
![image](https://cloud.githubusercontent.com/assets/28104515/25798503/b8676464-33e1-11e7-8143-b7efda13f2cf.png)

For Invoice Digitizing and email receiving channel (primary scope), we need to add next page in the workflow where we inform supplier about specific details from SOW/Routine description. this needs to be able to edit by us.

**Comment by gr4per** [comment]
This is about a supplier-customer relationship that defines which fields the customer requires to be in the invoice on top of any std required fields.

**Comment by gr4per** [comment]
We need customer specific supplierId as additional field

**Comment by gr4per** [comment]
We get the data for contacts from customer ERP in most cases (or SalesForce)
Add customerSupplierId in campaignContact (if not present)

For feeding back data we could export from onboarding and gather real supplier and user data.

**Comment by gr4per** [comment]
We also need to be able to impoort customerSupplierId into campaignContact.

**Comment by nczeranka** [comment]
CustomerSupplierId can/is now:
1. imported and/or edited in CampaignContacts (Campaign Step2)
2. passed into Voucher (onboarding - workflow.js)
3. added in InChannelContract  (einvoice-send) as soon as InChannelConfig with Customer terms and conditions is checked.
