### ISSUE TITLE
Supplier Dashboard - Profile strengt

### ISSUE THREAD

**Issue by ekmatts1** [OpusCapita/businessnetwork#29]
![image](https://cloud.githubusercontent.com/assets/28104515/25803670/3587f858-33f8-11e7-8ec0-e08435178bf5.png)
Next step to building up supplier profile strength by adding information to the subsections of; 
- Add financial data
- Add contacts
- Add certificates

For suppliers to add information themselves.

**Comment by gr4per** [comment]
How sure are we about user and access rights?
If we aim for june, we should split this and do contacts/ financial data / certificates early (easy copy paste).
And have a separate card for later that allows turning a contact to a user.
User administration will also be separate as it requires ACL editing.

**Comment by gr4per** [comment]
I think we wont even make certificates and financials.
Otherwise implemented by:
https://github.com/OpusCapita/supplier/issues/64
