### ISSUE TITLE
Get UI language (static + api) from user.profile.languageId and allow switching

### ISSUE THREAD

**Issue by gr4per** [OpusCapita/businessnetwork#31]
Login/Registration pages need to just reload in case language is changed in drop down
(no authenticated user)

SPAs need to switch UI language based on user.profile.languageId

We need switching in the horizontal header/user menu (where logout is, add Language)
Allow user to pick from supported UI languages (english, german)

This requires token refresh, too.

https://github.com/OpusCapitaBusinessNetwork/api-gw/projects/1
https://github.com/OpusCapita/bnp/issues/66
https://github.com/OpusCapita/einvoice-send/issues/6
https://github.com/OpusCapita/onboarding/issues/134
https://github.com/OpusCapita/invoice/issues/14

**Comment by kwierchris** [comment]
Have to check if this is still the case.
