### ISSUE TITLE
Add support contact information

### ISSUE THREAD

**Issue by kwierchris** [OpusCapita/businessnetwork#38]
Add support contact information to front-end. 

# Which information?
Details on support email and phone should be configurable via Consul:
- support.phone
- support.email

As default use:
- email: customerservice.de@opuscapita.com
- phone: +49 231 3967 350

# Where?
Best would be to place it in the user menu directly above the logout entry.

**Comment by celber** [comment]
Unclear to me, sorry. Can you describe details?

**Comment by kwierchris** [comment]
Please ignore this until it is assigned to a person or the backlog.
