### ISSUE TITLE
CampaignContacts - Handling of more than 3000 entries

### ISSUE THREAD

**Issue by nczeranka** [OpusCapita/businessnetwork#42]
We have to handle ~3000 CampaignContacts in one Campaign.

# Test run

Type | Contact Count | Duration in Seconds | Created | Updated | Error
-- | -| -| -| -| -
Insert | 200 | 8 | 200 | 0 | 0
Update| 200 | 5| 1 | 199 | 0
Update| 200 | 5| 1 | 199 | 0
Insert | 1000 | 29 | 1000| 0 | 0
Update| 1000 | 22 | 9 | 991 | 0
Update| 1000 | 22 | 9 | 991 | 0
Insert | 2903 | > 60 |  - | - | - 
Update| 1000 | 55 | 52 | 2851 | 0

Insert with 2903: As the feedback after a minutes we got a notification with success, but import is still running - finally 2903 Contacts created in db.

Additional issues:
- Firstname and Lastname could not be provided
- the Contact-Editor took a couple of seconds to render ~2900 Contacts 
- Contacts are initially shown when switching to another Campaign. This results for a big count of contacts in:
  - Wrong Contacts are shown while loading the correct ones
  - It slows down Campaigns with a low number of Contacts when switching from a high Contact count Campaign
- A couple of the Contacts seems to be lost in the Editor, when opening the big bunch. (2850 vs. 2903)

# Issues/Tasks
- We need a paging of the contacts list.
- Filtering on fields xxx would be helpfull
- Change the layout of the Contract list into one line -> complete width of the page
- Open an overlay for the editor (not side by side with the list)
- Asure that old Contact data is not initially used when opening the Contact editor again.
- Import is too slow - especially for synchonous import. 
- Synchronous import for Contact Excel with ~2600 entries takes more than 1 minutes, which results in a notification claiming success, although the importer is not done so far.
  - Add a comment that the import is designed for about xx contacts
  - Import the importer speed
  - asynchronous import ??? To be discussed!
- Assure that update import is properly working.

**Comment by gr4per** [comment]
To my knowledge this is covered ?

**Comment by nczeranka** [comment]
Main issues are solved.
Further enhancements will be covered by extra ticket (like introduction of new tables component, check key handling for update import, ...)
