### ISSUE TITLE
Terms of use / (Nutzungsbedingungen -DE -  in progress)

### ISSUE THREAD

**Issue by ekmatts1** [OpusCapita/businessnetwork#51]
Implement check-box for supplier to accept OC BNP terms of use - first version in english - in registration process. TOU approved by legal. 
![terms_of_use_in_registration1](https://user-images.githubusercontent.com/28104515/30025114-484015ca-9177-11e7-9842-9f314dc5c83a.png)

**Comment by ekmatts1** [comment]
Adding the text for the "Terms of Use" due to suppliers acceptance of the same. Se #51 #52

These Terms of Use govern the use of OpusCapita’s Business Network Portal (“BNP”). The Service enables suppliers to send transaction documents. By accessing the Service, the supplier agrees to these terms, which will bind to
[Business_Network_Portla_Terms of Use_20170904.pdf](https://github.com/OpusCapita/businessnetwork/files/1274601/Business_Network_Portla_Terms.of.Use_20170904.pdf)
 an agreement (“Agreement”). 

1	GENERAL 
1.1	In this document OpusCapita Group Oy is called OpusCapita. Supplier registering for the use of OpusCapita’s services is called Supplier. Party and Parties mean Supplier and/or OpusCapita. Customer means the recipient of Supplier’s Transaction Document.
1.2	In this document Service(s) refer to OpusCapita’s cloud based onboarding service to establish invoice flow from Supplier to a Customer.  The Service is under development and is currently made available for piloting purposes. 
1.3	Transaction Document means an invoice or other document which Supplier is permitted to send through the Service.
2	GENERAL OBLIGATIONS OF THE PARTIES
2.1	OpusCapita is responsible for providing the Service in a professional, workmanlike manner and ensuring that Supplier material is electronically transferred to the recipient in accordance with the agreed data transfer method and in the agreed document format
2.2	Supplier is responsible for fulfilling the then current prerequisites and requirements for the use the Service which is available at BNP. The supplier is responsible for the content relating to Transaction Documents and compliance with laws and regulations regarding its bookkeeping, accounting principles, tax, transfer price practices and following the instructions of applicable authorities.  Supplier shall ensure that the Transaction Documents do not infringe copyrights or other rights, best practices, applicable laws or orders or instructions issued by local authorities. 
3	SERVICES
3.1	OpusCapita shall configure and make the Service available in due course after successful registration by the Supplier. The supplier may use the Service for the purpose of sending Supplier’s Transaction Documents to the recipients. 
3.2	OpusCapita is constantly developing the Service and Service production environments based on the discovered development needs and feedback or due to changes in legislation or decisions of authorities. The supplier is responsible for its cost to ensure that Supplier’s systems support the changes in the Service.   
3.3	OpusCapita may suspend the Service due for example to installations of or changes or maintenance to the Services. OpusCapita may also suspend the Service in the event of a breach by Supplier of its obligations hereunder. 
3.4	OpusCapita’s liability for Transaction Document shall commence once Supplier material has been received by OpusCapita and shall end when Transaction Document is delivered electronically.  
3.5	Records of receipts and deliveries of Transaction Documents in OpusCapita’s information systems constitute proof of receipt or delivery of Transaction Documents. Information connected to the provision of the Service is verified from the above mentioned OpusCapita’s information systems.
3.6	OpusCapita is not responsible for verifying the accuracy of the content of Transaction Documents. OpusCapita will not modify the content other than for purposes of formatting, validating and transmission. The obligations of OpusCapita do not relieve Supplier from its obligations to comply with all applicable laws, including VAT requirements. All legal and commercial transactions to which the content of Transaction Documents relates are solely a matter for Supplier and the recipient of Transaction Documents.
3.7	Any storage of Supplier material and the terms and conditions for such storage in connection with the Service shall be subject to an agreement between the Parties. If not otherwise agreed in the Agreement, OpusCapita is entitled to destroy any Supplier material in its possession after 1 month following the fulfillment of the Service. 
4	INFORMATION SECURITY
4.1	The information security policy of OpusCapita Group directs the goals, responsibilities, and practices for information security management in OpusCapita Group.  OpusCapita’s information security management is developed in accordance with the common security principles in OpusCapita´s field of operation.  More information is available upon request.
4.2	The Parties shall ensure the data security of their information systems, and that their information systems are duly protected.
5	PERSONAL DATA
5.1	OpusCapita may process personal data provided by Supplier during the registration process for the purposes of providing the Service, such as name and email address of Supplier’s contact person. OpusCapita processes personal data in accordance with its privacy policy, which is available at www.opuscapita.com/privacy. 
5.2	With regard to personal data included in Transaction Documents, Supplier shall be the personal data controller for the use of whom personal data is collected and OpusCapita the processor of personal data. Supplier shall ensure that it has a right to process and enable personal data to be processed by the OpusCapita in manner and format used in the Service. Supplier shall, as part of ordering and agreeing on the Service, ensure that the Agreement sets out the subject-matter and duration of the processing, the nature and purpose of the processing, the type of personal data and categories of data subjects, as well as the obligations and rights of Supplier as the controller, together with the related data processing instructions, in accordance with the requirements of the general data protection legislation. 
5.3	OpusCapita undertakes to process personal data included in Transaction Documents in the Service in accordance with the Agreement. If Supplier issues new instructions for the processing of personal data after the signing of the Agreement, such instructions will be handled as a change request.
Parties undertake to implement such technical and organizational measures as are appropriate to optimize their respective business practices whilst ensuring a level of security required by the general data protection legislation and protecting personal data from unauthorized processing, destruction or alteration. Due to the requirement of cost-efficiency in the provision of Services, OpusCapita reserves the right to implement appropriate technical and organizational measures in its Service in a uniform manner across its customer base, taking into account any mandatory requirements of specific customer groups or clientele deriving from the general data protection legislation.
5.4	Upon Supplier’s request, a specific data protection agreement in the form of OpusCapita’s service model template will be executed. The terms of such data processing agreement shall take precedence in governing the processing of Supplier’s personal data.
5.5	OpusCapita shall be entitled to use a subcontractor identified at the time of concluding the Agreement or otherwise notified to the Supplier as detailed below, to process Supplier’s personal data in connection with the provision of Service, in accordance with the then applicable general data protection legislation. OpusCapita shall notify Supplier of any changes to the subcontractors it uses. Within 30 days from receipt of such notice, Supplier may provide its written and justified rejection of the use of one or more subcontractors identified in the notice. If Supplier provides such a notice of rejection, OpusCapita may give written notice of new fees or charges to be invoiced by OpusCapita to correspond with any change in the costs of processing of data as may result from Supplier’s rejection of the use of a subcontractor, or terminate the Agreement with effect of no less than thirty (30) days from Supplier’s notice of rejection. In case Supplier does not provide a notice of rejection in accordance with this clause, Supplier is deemed to have accepted the use of the subcontractors. Supplier reserves the right to provide notice of any changes to its data protection processes or to the subcontractors it uses on its website, in the service task tracking system or otherwise electronically, provided that Supplier’s contact person for the Services or other representative is provided notice thereof and has access to such notices.
6	CONFIDENTIALITY 
6.1	The Parties shall keep confidential information concerning the other Party, their customers their business operations or relationships, and any other information and material regarded as confidential, including, but not limited to any material and information provided by the Parties in connection with the provision of the Service. 
6.2	The obligations set out above will not apply to information which
	Is in the public domain at the time of disclosure or later becomes part of the public domain through no fault of the receiving Party; or
	Were created or rightfully known by the receiving Party prior to disclosure by the disclosing Party; or
	Is disclosed to the receiving Party by a third party who did not require confidentiality obligation; or
	Was independently developed by the receiving Party without the disclosing Party´s confidential information.
6.3	The Parties shall not reveal any confidential information or material to a third party without the written consent of the other Party. However, OpusCapita may distribute on a need basis materials and information required for the provision of the Services to companies within the same group of companies and to the subcontractors it uses ensuring that the materials and information will be kept confidential, and that information will not be used except for the purposes for which the distribution was made.
6.4	This confidentiality obligation shall remain in effect for three (3) years after the termination of the Agreement unless the applicable legislation or governmental decrees require a longer period.
6.5	 Despite what has been stated above, OpusCapita shall be entitled to use Supplier’s name and logo as a reference in OpusCapita's marketing.
7	SERVICE ERRORS
7.1	If Supplier wishes to lodge a complaint concerning an error in the Service, Supplier shall do so within 30 days of the point in time when OpusCapita has delivered or should have delivered the Service. OpusCapita´s liability for errors or delays does not extend to errors or delays caused directly or indirectly by Supplier or any acts or omissions of Supplier or by a third party under Supplier responsibility (such as the recipient of Supplier material).
7.2	OpusCapita does not warrant that the Service shall be uninterrupted and/or error-free. OpusCapita disclaims all implied warranties or conditions, including, but not limited to, the implied warranties or conditions of satisfactory quality, merchantability and fitness for a particular purpose.
8	LIMITATION OF LIABILITY
OpusCapita’s does not accept liability for indirect, consequential or special damages including loss of information or changes in information, loss of profit or business opportunity or loss of anticipated savings. OpusCapita’s total aggregate liability for any and all events giving rise to any liability shall, in total, not exceed an amount equal to the fees and charges paid or payable Supplier for the Services which gave cause to the claim. Where no such fees and charges are payable Supplier acknowledge and agree that the OpusCapita’s total aggregate liability shall be nil and that such a sum is reasonable on the basis that the Service has been provided free of charge. The limitations of liability provided above shall not apply to breaches of confidentiality or in cases of intentional misconduct or gross negligence.
9	FORCE MAJEURE
The Parties shall be released from adhering to their obligations under the Agreement and liability for damages in force majeure circumstances, such as a strike, a lockout, boycott, blockades, accidents, actions taken by the authorities and other circumstances which the Parties have been unable to avoid and whose consequences they have been unable to prevent. 
10	INTELLECTUAL PROPERTY RIGHTS 
10.1	OpusCapita shall retain all rights, including, but not limited to proprietary rights, copyright and other intellectual property rights, to the Services and the related material and computer programs. 
10.2	Supplier shall retain all rights, including, but not limited to proprietary rights, copyright and other intellectual property rights, to   Transaction Documents. OpusCapita has the right to use Transaction Documents only to provide the Services. OpusCapita may, however, use the data included in Transaction Documents and the data arising out of handling of Transaction Documents provided that such data is anonymized in a manner that it is not identifiable to Supplier or a person. 
10.3	Both Parties ensure that they have acquired all of the intellectual property rights and licensing rights necessary for the provision and use of the Service. Each Party shall procure and uphold all intellectual property rights and licensing rights relating to the use of any third party material, which may be necessary for the provision or use of the Services
11	ASSIGNMENT 
The Parties are not entitled to assign or transfer the Agreement between Supplier and OpusCapita or part of it without the other Party's written consent. OpusCapita is however entitled to transfer the Agreement or part of it without the consent of Customer to a subsidiary of OpusCapita or any company belonging to the same group of companies or to a third party acquiring the business that is subject to the Agreement. 
12	APPLICABLE LAW AND SETTLEMENT OF DISPUTES
The Agreement shall be governed by the laws of Finland excluding the choice of law stipulations. Any disputes between the Parties shall primarily be resolved through mutual negotiations. If agreement cannot be reached in these negotiations, the dispute shall be finally settled by arbitration in accordance with the Arbitration Rules of the Finland Chamber of Commerce. The procedure shall take place in Helsinki in the English language. The number of arbitrators shall be one.

**Comment by ekmatts1** [comment]
Text in pdf.
[Business_Network_Portla_Terms of Use_20170904.pdf](https://github.com/OpusCapita/businessnetwork/files/1274707/Business_Network_Portla_Terms.of.Use_20170904.pdf)

**Comment by gr4per** [comment]
Done
